export interface UnitTypes {
   millisecond: string,
   ms: string,
   second: string,
   s: string,
   minute: string,
   m: string,
   hour: string,
   h: string,
   day: string,
   d: string,
   week: string,
   w: string,
   month: string,
   mo: string,
   year: string,
   y: string,
   century: string,
   c: string,
   millenium: string,
   mi: string
}
